environment:
  name: prod
  project: cdf-bootcamp-77-prod
  type: prod
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee
variables:
  modules:
    bootcamp:
      CDF_PROJECT: cdf-bootcamp-77-prod # ex. cdf-bootcamp-01-prod
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      # This is related to the cluster where the CDF project is hosted.
      CDF_URL: https://westeurope-1.cognitedata.com
      IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env
      # Groups
      # OBJECT ID FOR PROD/PROD DATA PIPELINE OEE ENTRA GROUP
      data_developer_source_id: ba506893-a4f9-46be-b9ec-b4c27dcccd08
      data_pipeline_oee_source_id: 4cc023b-19d5-4c79-83cf-cf66ddabb504
      # OBJECT ID FOR PROD/PROD ADMIN TK ENTRA GROUP
      readwrite_source_id: 361445d0-41ea-41f0-81ea-abe3b42855fd
      # OBJECT ID FOR PROD/PROD ADMIN TK ENTRA GROUP
      readonly_source_id: 361445d0-41ea-41f0-81ea-abe3b42855fd
      # OBJECT ID FOR PROD/PROD ICAPI EXTRACTORS ENTRA GROUP
      icapi_extractors_source_id: 91761e24-287c-4f48-87ad-5adc6b6e9d2b
      # Client Ids
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee
